DROP TABLE IF EXISTS lines;
DROP TABLE IF EXISTS sketches;

CREATE TABLE sketches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sketch_id INTEGER NOT NULL,
    start_x REAL NOT NULL,
    start_y REAL NOT NULL,
    end_x REAL NOT NULL,
    end_y REAL NOT NULL,
    FOREIGN KEY (sketch_id) REFERENCES sketches (id)
);